version: '3'
services:
  swarm-lb:
    image: cecchisandrone/swarm-lb:0.0.1
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    environment:
    - ACTIVE_BACKEND=swarm-backend-green
    - BACKUP_BACKEND=swarm-backend-blue    
    ports:
    - 80:80
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 0s
  swarm-backend-green:
    image: cecchisandrone/swarm-backend:0.0.1
    environment:
    - ENVIRONMENT=GREEN
    ports:
    - 4000    
    deploy:
      placement:
        constraints: [node.labels.environment == green]
  swarm-backend-blue:
    image: cecchisandrone/swarm-backend:0.0.1
    environment:
    - ENVIRONMENT=BLUE
    ports:
    - 4000    
    deploy:
      placement:
        constraints: [node.labels.environment == blue]
  visualizer:
    image: manomarks/visualizer
    ports:
    - "8080:8080"
    #stop_grace_period: 1m30s
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  debug:
    image: busybox
    command: ping swarm-backend-blue
  galera1:
    image: erkules/galera:basic
    command: --wsrep-cluster-address=gcomm:// --wsrep-new-cluster
    hostname: galera1
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    ports:
    - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.hostname == default]
  galera2:
    image: erkules/galera:basic
    command: --wsrep-cluster-address=gcomm://galera1
    hostname: galera2
    ports:
    - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.hostname == swarm-1]
      restart_policy:
        condition: on-failure
        delay: 10s
  galera3:
    image: erkules/galera:basic
    command: --wsrep-cluster-address=gcomm://galera1
    hostname: galera3
    ports:
    - "3309:3306"
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.hostname == swarm-2] 
      restart_policy:
        condition: on-failure
        delay: 10s